[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "audiobooktools"
version = "0.1.0"
description = "Offline Audiobook Library and Tools"
readme = "README.md"
requires-python = ">=3.11"
license = { text = "MIT" }

authors = [
    { name = "Terry Yu" }
]

dependencies = [
    "ebooklib>=0.19",
    "beautifulsoup4>=4.13",
    "lxml>=5.3",
]

[project.optional-dependencies]

dev = [
    "black",
    "ruff",
    "pytest",
]

[tool.setuptools]
packages = ["audiobooktools"]

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
]
